name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-go
      - id: tool-versions
        run: awk '{ print $1"="$2 }' .tool-versions >> $GITHUB_OUTPUT
        shell: bash
      - uses: tibdex/github-app-token@v2
        id: create-iat
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: 42850289
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: "v${{ steps.tool-versions.outputs.goreleaser }}"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.create-iat.outputs.token }}
